examples/pairwise/config.xml, src/core/Tree.js, src/tags/visual/Style.js
config:
```html
<View>
<HyperText><h1>Hello</h1></HyperText>
</View>
```
=> Parsing HyperText differently, now you can put in html right into the

src/components/Waveform/Waveform.module.scss
Fixes heartexlabs/label-studio#195
=> Fix Waveform width with reset.css applied

src/components/ImageTransformer/ImageTransformer.js, src/mixins/Tool.js, src/tags/control/Brush.js, src/tags/control/Ellipse.js, src/tags/control/KeyPoint.js, src/tags/control/Label.js, src/tags/control/Polygon.js, src/tags/control/Rectangle.js, src/tags/object/Image.js, src/tools/Manager.js, src/tools/Polygon.js
* Simplify tools a bit
* Unselect other labels and tools
* Fix persisted ImageTransformer
=> Allow different types of labels to be in one Image

src/regions/EllipseRegion.js, src/tags/control/Ellipse.js, src/tags/object/Base.js, src/tags/object/Image.js, src/tools/Ellipse.js, src/tools/KeyPoint.js, src/tools/Rect.js
* correct `completion()` getter for Image
* optional `fillColor` for Ellipse
* consider possible lack of any `*labels` states for Image object in
different checks
=> Bunch of small fixes for Rectangle and other tools

src/components/Entities/Entities.js, src/components/Entities/Entities.module.scss, src/components/Entity/Entity.js, src/components/Node/Node.js, src/components/Node/Node.module.scss, src/components/Relations/Relations.js, src/components/Relations/Relations.module.scss
* Highlight relations of selected region
* Show number and color of region in the corresponding relation
* Tidy up mock-up
* Fix alignment and text-overflow
* Rewrite Node/NodeMinimal
=> Improve and fix side panel styles

src/mixins/Visibility.js
Quick try to use multiple values for these params
=> Comma-separated whenLabelValue and whenChoiceValue

src/components/Waveform/Waveform.js
=> Show helpful messages on loading errors

config-overrides.js, package-lock.json, package.json, src/index.js
This PR fixes #55 
Previously it was impossible to import LabelStudio into a buildable bundle.
=> Support building for CommonJS module system

src/components/Settings/Settings.js, src/stores/CompletionStore.js, src/stores/RegionStore.js, src/stores/SettingsStore.js
1. Select regions after creating them
2. Display Labels in the Results sidebar by default
=> Two new settings

.github/workflows/build.yml, config-overrides.js
=> Export LSF as window global and module export

src/regions/PolygonPoint.js, src/regions/PolygonRegion.js
=> Remove polygon point by double click

e2e/tests/regression-tests/multiple-same-named-tools.test.js, src/tools/Manager.js
Fixing issue https://github.com/heartexlabs/label-studio/issues/202
=> Fix working with multiple same-named tools refers to the same image

src/components/ImageView/ImageView.js, src/components/RelationsOverlay/BoundingBox.js, src/components/RelationsOverlay/Geometry.js, src/components/RelationsOverlay/NodesConnector.js, src/core/Tree.js, src/mixins/Tool.js, src/regions/BrushRegion.js, src/tags/object/Audio.js, src/tags/object/HyperText.js, src/tags/object/TimeSeries.js, src/tags/visual/View.js, src/tools/Brush.js, src/tools/Erase.js, src/utils/canvas.js, src/utils/colors.js, src/utils/utilities.js
This pull request should improve usability in case of image segmentation using the brush tool.
Fixes:
- https://github.com/heartexlabs/label-studio/issues/492
=> Brush tool fixes and optimizations

package.json, src/components/RelationsOverlay/BoundingBox.js, src/components/RelationsOverlay/RelationsOverlay.js, src/components/RelationsOverlay/watchers/DOMWatcher.js, src/regions/AudioRegion.js, src/regions/HyperTextRegion.js, src/regions/ParagraphsRegion.js, src/regions/RichTextRegion.js, src/regions/TextAreaRegion.js, src/regions/TextRegion.js, src/regions/TimeSeriesRegion.js, src/stores/AnnotationStore.js
Relations break when the data loaded remotely (#202)
This PR fixes the issue for RichText and other network-related tags.
=> Fix relations for remotely loaded data

e2e/codecept.conf.js, e2e/fragments/AtImageView.js, e2e/helpers/MouseActions.js, e2e/tests/helpers.js, e2e/tests/regression-tests/image.regions-select.test.js, src/regions/PolygonRegion.js
It's more about polygons, but test covers all existence image regions.
=> Fix for selecting regions after drawing

src/assets/styles/global.scss, src/env/development.js, src/tags/control/Taxonomy.js, src/utils/utilities.js
- add maxUsages to limit selected items
- add required
- add leafsOnly to allow to select only leaf nodes
- fix and improve built-in search
=> Improve Taxonomy

examples/audio_regions/config.xml, src/env/development.js, src/regions/Result.js, src/tags/control/Number.js, src/tags/control/index.js, src/tags/visual/View.js
=> Add <Number/> tag

src/components/Label/Label.js, src/core/Hotkey.js, src/stores/AnnotationStore.js, src/stores/AppStore.js, src/tags/control/Label.js
1. most important - hotkeys stop working after interacting with text
and submitting task after that, because lack of scopes in unbindAll
2. there are still two hotkeys and actions to send a task - submit and
update; but now submit by hotkey will update the task if possible
3. ctrl+enter works even if some input focused
=> [fix] weird errors with hotkeys and submit

src/regions/RichTextRegion.js, src/tags/object/RichText/model.js, src/tags/object/RichText/view.js, src/utils/selection-tools.js
- remove scripts and iframes (actually replace them with stubs to keep the same amount of elements)
- iframe auto-height
- fix errors when regions are out of range (broken xpath/offsets)
=> Improve iframe-based HyperText labeling

src/tags/object/RichText/view.js
Calculate also using html height if document wasn't loaded correctly or fully
=> [fix] better iframe height calculation

src/mixins/HighlightMixin.js, src/tags/object/RichText/RichText.styl, src/tags/object/RichText/model.js, src/utils/html.js, src/utils/selection-tools.js
=> Fix `showLabels` param and related settings

e2e/fragments/ErrorsCollector.js
This should fix a terrible problem with e2e tests.
=> DEV-1428: Fix ResizeObserver error in E2E

src/stores/AppStore.js
- reset `initialized` flag
- fix `isSubmitting` flag for all `ctrl+enter` handlers
=> fix: DEV-1518: improve review performance

src/tags/object/TimeSeries.js
Add param `overviewWidth` to set default width in percents (default 25%)
=> feat: DEV-1490: TimeSeries overview width param

src/components/AnnotationTabs/AnnotationTabs.js, src/components/Annotations/Annotations.js, src/components/TopBar/Annotations.js, src/regions/Result.js, src/stores/AnnotationStore.js, src/utils/feature-flags.js
It will add ability to create new annotations already with some results from predictions
=> feat: DEV-1621: Add ability to create annotation with pre-created regions

src/components/Timeline/Views/Wave/Wave.styl, src/components/Timeline/Views/Wave/Wave.tsx
overlay timeline on top of waveform for full height timestamp tooltip
=> feat: dev-2039: timestamp tooltip on timeline

src/components/Timeline/Views/Wave/Wave.tsx, src/tags/object/AudioNext/model.js
add defaultscale to audio config params
=> feat: DEV-2040: Add default y-scale parameter

src/regions/PolygonRegion.js
null block points reduce polygon
=> fix: dev-1943: bboxes stop drawing

src/regions/PolygonRegion.js, src/tools/Polygon.js
write a new check for polygon points
=> fix: dev-2068: toolswitch-finish-drawing

src/mixins/DynamicChildrenMixin.js
=> fix: DEV-2096: DEV-2097: Fix basic functional of dynamic children

src/components/Node/Node.styl, src/regions/VideoRectangleRegion.js, src/tags/control/TextArea/TextArea.styl
DEV-2160: Fix region icon in Firefox
DEV-2164: OCR delete button width
DEV-2187: Moving regions between two kpoints
=> hotfix: DEV-2187: DEV-2164: DEV-2160: 2.2.6

src/components/TopBar/Controls.js
Use "comments:reject" interface
=> feat: DEV-2241: Show reject comment by settings toggle

src/components/HtxTextBox/HtxTextBox.js
Don't pass onChange to Paragraph
=> fix: DEV-2299: error in editable TextArea

src/components/Settings/Settings.js, src/core/settings/editorsettings.json, src/env/development.js, src/env/production.js, src/stores/SettingsStore.js
- Added defaultsettings.json with default settings configuration for editor
- Added an ability to set default settings when initializing the LSF
=> fix: DEV-1577: add default settings

src/assets/icons/annotation/index.ts, src/assets/icons/annotation/propagated.svg, src/assets/icons/annotation/removed.svg, src/components/CurrentEntity/AnnotationHistory.tsx, src/stores/Annotation/HistoryItem.js
- Add new History types
- Make MST history type loosely typed
=> feat: DEV-2387: New history types

src/components/CurrentEntity/AnnotationHistory.styl, src/components/CurrentEntity/AnnotationHistory.tsx, src/components/CurrentEntity/CurrentEntity.js, src/components/CurrentEntity/CurrentEntity.styl, src/stores/Annotation/Annotation.js
DEV-2398: fix disappeared draft state 
DEV-2428: unselect history items on click 
fix colors for active and hovered history items
=> fix: DEV-2290: history drafts fixes

src/tags/object/RichText/model.js
- I've changed the regex that remove scripts.
- I've added a new regex to remove all properties that starts with "on".
=> fix: DEV-2351: Hypertext-security

src/components/SidePanels/PanelBase.styl, src/components/SidePanels/SidePanels.styl, src/components/Taxonomy/Taxonomy.module.scss, src/components/Taxonomy/Taxonomy.tsx, src/components/TreeStructure/TreeStructure.tsx
add support for super long taxonomy text wrapping multiple lines
=> fix: DEV-1975: Taxonomy multi line items

src/utils/selection-tools.js
fixes https://github.com/heartexlabs/label-studio/issues/1931
=> fix: DEV-1592: get text after granularity applied

src/tags/control/Shortcut.js
- removed item.selected which is not necessary in this case
- added background as a new parameter
=> fix: DEV-2423: Add background as a new parameter

src/components/Timeline/Views/Wave/Wave.tsx
Increase the minimum and default zoom to 300, the min set for wave-surfer
=> fix: DEV-1714: X-axis zoom threshold

src/components/VideoCanvas/VideoCanvas.tsx, src/mixins/SyncMixin.ts, src/tags/object/AudioNext/model.js, src/tags/object/AudioNext/view.tsx, src/tags/object/Video/HtxVideo.js, src/tags/object/Video/Video.js, src/utils/TimeSync.ts
- fixed the bug video and audio wasn't sync when play speed was changed
=> fix: DEV-2207: sync speed between video and audio

src/regions/AudioRegion.js, src/tags/object/AudioNext/view.tsx
- Resolved the problem that the first segment was mimicking the second segment.
- ClassList was duplicating if user changes the segment
=> fix: DEV-2462: Changing label

src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx, src/stores/RegionStore.js
add unique render keys to labels that are displayed under two different tag names.
=> fix: DEV-2763: Multiple rendered labels in regions

src/tags/object/Video/VideoRegions.js
- User can't edit locked regions
=> fix: DEV-2146: Lock rect VideoRectangle

src/mixins/KonvaRegion.js
=> fix: DEV-2922: Selection box of rectangle region remains broken after hide/ unhide action

src/tags/control/Choice.js
i missed the hotkeys - issue should be resolved now
=> fix: DEV-2365: User is able to edit choice results imported as read-only

src/regions/BrushRegion.js, src/tags/control/DateTime.js, src/tags/control/Shortcut.js, src/tags/object/RichText/model.js, src/tags/visual/Collapse.js
Already merged by https://github.com/heartexlabs/label-studio/pull/2650
=> docs: Small fixes to some tag docs

src/tags/visual/Repeater.js
Compiled into https://github.com/heartexlabs/label-studio/pull/2788
=> docs: DEV-3081: Improve Repeater docs

src/components/TopBar/Annotations.js, src/components/TopBar/Annotations.styl
Reverts heartexlabs/label-studio-frontend#854
=> chore: revert: DEV-3074: Add line between draft and annotation on annotation list

src/components/TopBar/CurrentTask.js, src/stores/AppStore.js
Don't show Postpone button if it was clearly disabled
=> feat: DEV-3100: Interface "postpone" for button

src/components/App/App.js, src/components/App/App.styl, src/components/SidePanels/SidePanels.styl
=> fix: DEV-3353: Scroll fix review stream 

src/components/Comments/CommentItem.tsx, src/components/Comments/Comments.tsx, src/components/Comments/CommentsList.tsx, src/stores/Comment/Comment.js, src/stores/Comment/CommentStore.js
If edited display edited time in session
=> fix: DEV-3692: Comment edited session state

src/tags/object/TimeSeries/Channel.js
handle model id when view all ff is off
=> Fix: DEV-3748: Fix truncated timeseries rendering

src/tags/object/Video/HtxVideo.js, src/tags/object/Video/VideoRegions.js
check if the zoom is outside of the edge on each axis and reset region pan accordingly
=> fix: DEV-3759: Region changes position on scroll + zoom

src/lib/AudioUltra/Regions/Regions.ts, src/lib/AudioUltra/Visual/Visualizer.ts
resolves a bug where controls get blocked by hidden canvas when layers are hidden/collapsed
=> fix: DEV-3826: Toggling Audio interfaces should correctly update the view

src/core/TimeTraveller.js
The problem is in draft initialization with some data types.
=> fix: DEV-3917: Revert #1043

src/regions/AudioRegion.js, src/regions/AudioRegion/AudioRegionModel.js, src/regions/AudioRegion/AudioUltraRegionModel.js, src/tags/control/Brush.js, src/tags/control/KeyPointLabels.js, src/tags/visual/Repeater.js
- fix missed AudioRegion documentation in Audio tag after v3 release
- fix Brush example description
- add missed Repeater docs about pagination mode (added to LS directly)
=> docs: DEV-4153: Small docs fixes 

src/stores/AppStore.js
=> fix: LSDV-4539: Don't show history for wrong annotation

e2e/fragments/AtAudioView.js, e2e/tests/audio/audio-regions.test.js
I wasn't be able to reproduce the problem that QA reported, probably it was already fixed, so I just added e2e tests to cover this problem
NA
Na
NA
NA
no
no
NA
NA
=> chore: LSDV-4592: Add tests to validate if ghost regions are created on AudioV3

package.json, src/components/SidePanels/Components/LockButton.tsx, yarn.lock
=> fix: LSDV-4670: Fix frontend build

e2e/codecept.conf.js, e2e/fragments/AtSidebar.js, e2e/fragments/Modals.js, e2e/plugins/featureFlags.js, e2e/setup/feature-flags.js, e2e/tests/ocr.test.js, e2e/tests/textarea.skip-duplicates.test.js, src/tags/control/TextArea/TextArea.js, src/utils/feature-flags.ts
Request for a functional of preventing duplicates in `<Textarea/>` inputs
N/A
`<TextArea/>` gets new parameter called `skipDuplicates` which allows to keep submissions unique.
Can be used as:
```xml
<View>
<Audio name="audio" value="$audio"/>
<TextArea name="genre" toName="audio" skipDuplicates="true" />
</View>
```
There is no such functional right now.
N/A
Nope
Nope
N/A
`fflag_feat_front_lsdv_4659_skipduplicates_060323_short`
`TextArea`
=> feat: LSDV-4659: Add skipDuplicates parameter to TextArea

src/lib/AudioUltra/Controls/Player.ts
Corrects an issue where the localized sync of the audio playback to its visual timer was causing a near infinite loop in attempting to synchronize every update back to other sync tags. Now this just syncs the currentTime based on the time it took to buffer `locally` to the audio tag itself, and does not notify sync tags about this change as they are not relevant and need to stay within the single tag.
- [-] e2e (partially covered by current tests)
Video, Audio v3, Sync
=> fix: LSDV-4706: Video timeline segmentation plays correctly without micro stuttering issues

src/utils/feature-flags.ts
If the FF is set in the base file it cannot be overridden. 
Audio v3
=> fix: LSDV-4701: Removing feature flag from base file

e2e/.eslintrc.js, e2e/tests/image-list.test.js, src/mixins/Regions.js
LSDV-4682
Fixes issue when regions can shift on submission.
Regions don't shift anymore
Regions shift on submission
None
No
No
Labeling Interface, Image Segmentation
=> fix: LSDV-4682: Fix regions shifting in MIG scenario

e2e/codecept.conf.js, e2e/fragments/LabelStudio.js, e2e/helpers/Assertion.js, e2e/tests/image-list.test.js, src/components/ImageView/Image.js, src/components/ImageView/ImageView.js, src/regions/BrushRegion.js, src/regions/EllipseRegion.js, src/regions/KeyPointRegion.js, src/regions/PolygonRegion.js, src/regions/RectRegion.js, src/stores/Annotation/Annotation.js, src/tags/object/Image/Image.js
MIG feature caused a major data corruption which prevented users from using the feature.
By leveraging raw region results, LSF can now set image dimensions without loading actual images. Also, during the serialization phase, LSF will use existing regions' data when it's impossible to calculate data from an image.
When submitting an annotation, LSF will export existing region results instead of calculating from scratch. This is only applicable when a related image is not yet loaded.
We're always trying to export data based on the image, which is sometimes impossible.
None
No
No
None
Same as the MIG feature.
Labeling Interface, Image Segmentation
=> fix: LSDV-4676: Region corruption MIG

src/tags/visual/Repeater.js
=> docs: LSDV-4707: Remove Repeater from docs

src/tags/object/Video/VideoRegions.js
With *universal readonly* implementation, the Video Rectangles wasn't showing while drawing
Fix the small regression, now Video Rectangles is showing while drawing
NA
No
No
NA
No
=> fix: LSDV-4740: Video Rectangles are displaying while drawing

.github/workflows/release-set-version.yml
=> ci: SRE-471: Publish tags from LSF repo to LS

e2e/fragments/AtImageView.js, e2e/tests/image-list.test.js
=> test: Fix MIG tests

src/tags/object/AudioUltra/model.js
To better outline the splitchannels feature, and the requirements for more memory when enabled.
Audio
=> docs: LSDV-4874: Update audio documentation to outline splitchannels usage

src/components/Filter/Filter.tsx, src/components/Filter/FilterInterfaces.tsx, src/components/Filter/FilterRow.tsx, src/components/Filter/__tests__/filter-utils.test.tsx, src/components/Filter/filter-util.ts, src/components/SidePanels/OutlinerPanel/OutlinerPanel.tsx, src/components/SidePanels/OutlinerPanel/ViewControls.tsx
Add new the filter less or equal and greater or equal to the new filter component, it's not integrated with outliner component, so it's not possible to see it's working from the user's perspective
no
no
fflag_feat_front_dev_3873_labeling_ui_improvements_short
=> feat: LSDV-3025-8: Add less or equal and greater or equal filters

src/tags/object/Image/Image.js, src/tags/visual/Style.js
Docs are broken because of wrong format:
- `<>` should be escaped
- examples should contain xml directly, all comments go into `` html comments
=> docs: LSDV-4901: Style and Image docs fixes

src/components/Filter/Filter.tsx, src/components/Filter/FilterInterfaces.tsx, src/components/Filter/FilterRow.tsx, src/components/Filter/filter-util.ts, src/components/Filter/types/Boolean.js, src/components/Filter/types/Number.js, src/components/SidePanels/OutlinerPanel/OutlinerPanel.tsx, src/components/SidePanels/OutlinerPanel/ViewControls.tsx, src/stores/RegionStore.js
When filter is applied on the outliner, the filtered result is reflected to the list
no
no
na
fflag_feat_front_dev_3873_labeling_ui_improvements_short
=> feat: LSDV-3025-3: Integrate filter component into outliner

src/common/Pagination/Pagination.tsx, src/common/Select/Select.tsx, src/components/Filter/Filter.tsx, src/components/Filter/FilterDropdown.tsx, src/components/Filter/FilterInput.tsx, src/components/Filter/FilterInterfaces.tsx, src/components/Filter/FilterRow.styl, src/components/Filter/FilterRow.tsx, src/components/Filter/__tests__/Filter.test.tsx, src/components/Filter/__tests__/FilterRow.test.tsx, src/components/Filter/__tests__/filter-utils.test.tsx, src/components/Filter/filter-util.ts, src/components/SidePanels/OutlinerPanel/ViewControls.tsx, src/components/SidePanels/TabPanels/Tabs.tsx, tests/functional/specs/outliner/filter.cy.ts
The filter component now is able to filter multiple rules, using 'AND' and 'OR' as rules.
The filter component is not able to filter multiple rules, just 1 rule at once
No
No
NA
fflag_feat_front_dev_3873_labeling_ui_improvements_short
=> feat: LSDV-3025-11: Add functionality to filter with multiple rules

.github/workflows/cicd_pipeline.yml, .github/workflows/eslint.yml, src/configureStore.js
LSDV-4993
Changes how ESLint checks the files.
ESLint will only target changed files.
ESLint was targeting all files all the time.
None
No
No
None
None
CI, Linting
=> chore: LSDV-4993: Fix ESLint to target changed files only

tests/functional/package.json, tests/functional/yarn.lock
A hotfix to ensure cypress tests will work correctly on CI in parallel mode.
=> fix: Cypress test runner in parallel mode

src/components/SidePanels/TabPanels/SideTabsPanels.tsx
padding is not necessary when panels are not visible 
It removes padding on view all 
No padding on view all 
The padding for panels persist when they are not visible on view all 
N/A
N/A
N/A
N/A
N/A
Frontend Panels
=> fix: LSDV-5010: View all panel padding removed

.github/workflows/fun_tests.yml, src/components/SidePanels/DetailsPanel/RegionItem.tsx, src/components/SidePanels/OutlinerPanel/ViewControls.tsx, src/stores/Annotation/Annotation.js, src/stores/AppStore.js, tests/functional/package.json, tests/functional/specs/image_segmentation/image_regions.cy.ts, tests/functional/yarn.lock
Hotkey to hide regions (alt+H) were not working.
This fix is removing a duplicated hotkey call and changing the way that the hotkey to hide regions work, before it was possible to hide just 1 region at time, now it's possible hide multiple-selected regions.
none
no
no
na
na
=> fix: LSDV-4766: Toggle selected region visibility with hotkeys

src/components/BottomBar/BottomBar.js
There should be no bottom bar in view all mode 
This removes the bottom bar in view all mode
in view all mode there is no bottom bar 
in view all mode there is a bottom bar
N/A
N/A
N/A
N/A
N/A
bottom bar view all
=> fix: LSDV-5011: In view all mode there should be no bottom bar

src/components/SidePanels/TabPanels/utils.ts
new defaults for tab panels 
n/a
new defaults for tab panels 
just different defaults 
N/A
no
no
n/a
N/A
panel tabs frontend
=> feat: LSDV-5069: Create new defaults for panels and tabs

src/components/Filter/Filter.styl, src/components/Filter/Filter.tsx, src/components/Filter/__tests__/Filter.test.tsx, tests/functional/specs/outliner/filter.cy.ts
The filter button wasn't getting active when dropdown was opened
The filter button is getting on active state when dropdown is opened.
no
NA
no
NA
NA
=> fix: LSDV-5065: Set filter button active when dropdown is opened

src/components/BottomBar/Controls.styl, tests/functional/specs/outliner/filter.cy.ts
NA
Revert the labeling editor CTA button color
NA
no
no
NA
NA
=> fix: LSDV-5117: Revert labeling editor CTA buttons color

src/components/TopBar/TopBar.styl
=> fix: LSDV-5115: Fix height of tasks header row on quick view

src/common/TimeAgo/TimeAgo.tsx, src/components/AnnotationsCarousel/AnnotationButton.styl, src/components/TopBar/TopBar.js, src/components/TopBar/TopBar.styl
=> fix: LOPS-170: Labeling ui annotation tab improvements

e2e/tests/image-list.test.js, src/utils/feature-flags.ts
=> chore: LSDV-5109: Rename MIG FF key

public/index.html, src/common/Button/Button.styl, src/common/Button/Button.tsx, src/common/TimeAgo/TimeAgo.tsx, src/components/AnnotationsCarousel/AnnotationButton.styl, src/components/AnnotationsCarousel/AnnotationsCarousel.styl, src/components/BottomBar/Controls.js, src/components/BottomBar/CurrentTask.js, src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx, src/components/SidePanels/OutlinerPanel/TreeView.styl, src/components/TopBar/CurrentTask.js, src/components/TopBar/CurrentTask.styl, src/components/TopBar/TopBar.js, src/components/TopBar/TopBar.styl, src/stores/AppStore.js
=> fix: ls-release: 1.8.0 hotfix

public/index.html, src/components/AnnotationsCarousel/AnnotationsCarousel.styl, src/components/BottomBar/CurrentTask.js, src/components/TopBar/CurrentTask.js, src/components/TopBar/CurrentTask.styl, src/components/TopBar/TopBar.styl, src/stores/AppStore.js
This reverts commit 4aa1091c8c2a6005ea09ba52c2ad264eaf68df4b.
=> feat: LSDV-3104: Revert task navigation standardization

src/common/Button/Button.styl, src/components/BottomBar/Controls.js, src/components/BottomBar/Controls.styl
New UI Submit color was not required as it's the same as in old UI, but it was too specific to override all other states like disabled.
=> fix: LSDV-5131: Fix Submit button disabled state

e2e/tests/regression-tests/annotation-button.test.js, src/components/AnnotationsCarousel/AnnotationButton.styl, src/components/Comments/CommentForm.tsx, src/components/TopBar/CurrentTask.js
cf102b71d37008b11450a39f8055804e7c77b328
324a9d3899e0059230e1e38e76120dc74ddcae0f
=> fix: 1.8.0 cherrypick 2023 05 25

src/components/SidePanels/TabPanels/SideTabsPanels.tsx, src/components/SidePanels/TabPanels/utils.ts
=> fix: LSDV-5160: Hide comments tab on UI Preview

src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx, src/components/SidePanels/OutlinerPanel/TreeView.styl, src/components/SidePanels/TabPanels/Tabs.tsx
=> fix: LSDV-5161: Fix confidence score design to match with new labeling ui

src/components/Ranker/Item.tsx, src/tags/control/Ranker.js
Also fixes LSDV-5168, LSDV-5166 and LSDV-5169
Store original List items in result to track their changes too, this allows to rollback any changes made to Ranker. Full Ranker state is serialized now.
=> fix: LSDV-5167: Ranker undo/redo

src/components/SidePanels/Components/LockButton.tsx, src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx, src/components/SidePanels/OutlinerPanel/TreeView.styl
=> fix: LSDV-5145: Regions hover lock consistency

src/components/SidePanels/SidePanels.tsx, src/components/SidePanels/TabPanels/SideTabsPanels.tsx
There was a problem with ResizeObserver from our panels, when user moved item to another column making it higher. That happens only in collapsed mode, and ResizeObserver is actually not needed there.
In Preview items in Ranker can't be dragged in a way that increases any column's height. ResizeObserver went in an infinite loop because of this.
Disables ResizeObserver in collapsed mode (mostly used in Preview)
_(for bug …
=> fix: LSDV-5202: Fix Ranker d-n-d in Preview

src/components/AnnotationsCarousel/AnnotationsCarousel.styl, src/components/SidePanels/SidePanels.tsx, src/components/SidePanels/TabPanels/SideTabsPanels.tsx
bcb176dac85337b88887cfff788fb8238dc31bfa
e81f5dd88041565f13b6ecaa297bb4d68c7b8e28
=> chore: 1.8.0 cherrypick 2023 05 31

src/assets/icons/close.svg, src/assets/icons/index.tsx, src/common/Toggle/Toggle.styl, src/components/AnnotationsCarousel/AnnotationButton.tsx, src/components/Ranker/Ranker.tsx, src/components/Settings/Settings.js, src/components/Settings/Settings.styl, src/components/SidePanels/OutlinerPanel/TreeView.styl, src/core/settings/editorsettings.js, src/tags/control/Ranker.js, src/tags/control/__tests__/Ranker.test.ts, src/tags/object/List.js
536042b03a7f3b8ea950aa482d131c744ac8b252
3909fd6a0365c8b1aa95c133020ceb7ca2469be5
4302d94a0a3e7f736008ec792f7b41c02cd86210
2e611ab5ad94d41099844f6a9601dfc94ff086f1
=> chore: 1.8.0 cherrypick 2023 06 01

src/components/BottomBar/CurrentTask.js
Postpone functionality was broken in OSS builds because of a dependent feature that is not a true requirement for this to work.
LabelStream, Postpone Tasks
=> fix: LSDV-5235: Postpone should not require FF to operate

e2e/package.json, e2e/yarn.lock, yarn.lock
=> fix:  LSDV-E-135: Dependabot updates

src/components/App/App.js, src/components/BottomBar/Controls.js, src/components/Comments/CommentForm.tsx, src/components/SidePanels/TabPanels/SideTabsPanels.tsx, src/components/SidePanels/TabPanels/__tests__/utils.test.tsx, src/components/SidePanels/TabPanels/types.ts, src/components/SidePanels/TabPanels/utils.ts, src/stores/AppStore.js
"Cherry-picking" #1379
* fix: lsdv-5001: skip comments when required will open the comments panel and focus on the comments input
* tests
* tests and imports
* fix import error
* Update src/components/BottomBar/Controls.js
* Update src/stores/AppStore.js
* clear tooltip on unmount not load
* improve find panel tab logic
* fix find panel function
--------- …
=> fix: LSDV-5001: Skip comments panel focus

src/lib/AudioUltra/Regions/Segment.ts, src/regions/AudioRegion/AudioRegionModel.js, src/regions/AudioRegion/AudioUltraRegionModel.js, src/utils/feature-flags.ts
When user is trying to lock a region using the outliner, the region on the audio form wasn't being locked and the user was able to move, resize and delete the region.
User is not able anymore to move, resize or delete the region if it's locked
=> fix: LSDV-1666: Fix lock option isn't locking audio regions

.github/workflows/sync-pr-ls.yml, .github/workflows/sync-pr-lse.yml
=> ci: SRE-541: Dynamic GH org name

.github/workflows/sync-pr-ls.yml, .github/workflows/sync-pr-lse.yml
=> ci: Fix syntax

.github/workflows/cicd_pipeline.yml, .github/workflows/release-set-version.yml
=> ci: SRE-541: Local workflow call

src/tags/object/Paragraphs/HtxParagraphs.js, src/tags/object/Paragraphs/Paragraphs.module.scss, src/tags/object/Paragraphs/model.js, src/utils/feature-flags.ts
Add maxheight as a config attribute with a default of 500px and style scrolling window
N/A
The config attribute defines the maximum height of the scrolling window 
it takes up as much space as it's contents will allow 
none
no
no
we could have used flex box or javascript to calc the available space 
fflag_feat_front_lsdv_e_278_contextual_scrolling_short
=> feat: LSDV-5296: Scroll container max height

src/tags/object/Paragraphs/HtxParagraphs.js
=> fix: LSDV-5296: Disconnect observer

src/tags/control/Choices.js, src/tags/control/Taxonomy/Taxonomy.js, tests/functional/data/control_tags/taxonomy.ts, tests/functional/specs/control_tags/taxonomy.cy.ts
=> fix: LSDV-4853: Add warning message when user selects more choices than maxUsages

src/tags/control/TextArea/TextArea.js
=> fix: LSDV-5400: LLM suggestions from textarea

src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx, src/components/SidePanels/OutlinerPanel/ViewControls.tsx, src/stores/RegionStore.js, tests/functional/specs/outliner/hide-all.cy.ts
If regions was grouped by tools on outliner, the show/hide icon in the group section are hiding just the first region in the list
The show/hide icon in the group section when regions is grouped by tools is hiding and showing all regions inside that group
=> fix: LSDV-5188: Fix show/hide icon that wasn't working if regions was grouped by tools

src/tags/object/RichText/domManager.ts
The last RichText optimizations cause loosing focus in config editor because of reseting selection ranges. So it is painful to edit the config.
This fix restores selection after RichText rendering. And also it reanimates an active element by blurring and focusing it again.
It does not
It does not
I'd like to know that.
`fflag_feat_front_lsdv_4620_richtext_opimization_060423_short`
The approach of solving the problem (blur and focus again) could have unpredictable consequences. But it's better know and quick solution for now.
`RichText`, `initialization`
=> fix: LSDV-5432: Fix losing focus in CodeMirror config editor

src/utils/reactCleaner.js, tests/functional/yarn.lock
After previous memory leaks fixes some icons becomes broken
This fix prevents processing svg tags while cleaning react cache.
N/A
It should not.
Nope
N/A
`fflag_fix_front_lsdv_4620_memory_leaks_100723_short`
`Svg icons`, `Image View Toolbar`
=> fix: LSDV-5446: Fix disappearing icons

yarn.lock
Fixes https://github.com/HumanSignal/label-studio-frontend/pull/1495 https://github.com/HumanSignal/label-studio-frontend/pull/1498
=> ci: Fix several vulnerabilities from dependabot

src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx, src/regions/VideoRegion.js, src/utils/feature-flags.ts
Works only on select from Outliner.
=> feat: LEAP-187: Skip Video to region start on select

src/components/NewTaxonomy/NewTaxonomy.tsx
`maxUsages` should limit number of items that can be selected in current taxonomy (per object or per region). All unselected items should be disabled upon reaching the limit. Already selected items should be available, so user can unblock taxonomy by unselecting wrong one.
It improves it a little by simplifying recursive function.
But there are more checks now when maxUsages reached, which can reduce performance a little.
nope
solution is pretty straightforward and similar to that one we have in old taxonomy.
`fflag_feat_front_lsdv_5451_async_taxonomy_110823_short`
Taxonomy
=> fix: LEAP-250: Fix maxUsages for New Taxonomy

src/tags/control/Taxonomy/Taxonomy.js, src/utils/feature-flags.ts
User must be able to use the prop apiUrl with basic authorization.
Add the possibility to user use the prop apiUrl as `https://username:password@rest.of.url/` and taxonomy will parse it to authenticate
no
no
no
no
fflag_feat_front_lsdv_5451_async_taxonomy_110823_short
=> fix: LEAP-255: Parse username and password from basic auth URL and use for API calls

package.json, yarn.lock
There is a problem with the version that the software is using for postcss
Update the package postcss to version 8.4.31
postcss updated to version 8.4.31
=> fix: LEAP-314: Fix Github vulnerabilities

src/components/NewTaxonomy/NewTaxonomy.tsx, src/components/NewTaxonomy/TaxonomySearch.tsx
The taxonomy items were collapsing when the user closed the dropdown, even if the user hadn't searched for anything.
The state of the dropdown is being maintained when the user interacts with the taxonomy items.
=> fix: LEAP-345: Fix taxonomy items collapsing when dropdown is closed

src/tags/control/Taxonomy/Taxonomy.js
- Removed feature flag note
- Added "beta" to apiUrl description
=> docs: DOC-161: Add beta tag for external taxonomy

src/tags/object/RichText/model.js, src/utils/feature-flags.ts
* fix: LEAP-466: Don't sanitize text tasks
* Fix text case lol
=> fix: LEAP-466: Don't sanitize text tasks (#1646)

src/LabelStudio.js, src/regions/VideoRegion.js
=> chore: Cherry picked OPTIC-353 into release 1.11.0
