HumanSignal/label-studio-frontend

- README.md
Fix the link to `label-studio`, and update the link to `converter`
> Fix urls in README.md

- examples/image_bbox/completions/1.json
- scripts/copy.sh
When building the project as per instructions in README.md one currently encounters two errors: 
1. 
```bash
> bash scripts/copy.sh
cp: target 'src/examples/' is not a directory 
``` 
Once fixed, one gets: 
2. 
```
Failed to compile
./src/examples/image_bbox/index.js
Module not found: Can't resolve './completions/1.json' in 'path/to/label-studio-frontend/src/examples/image_bbox' 
``` 
This PR fixes both issues by tweaking `scripts/copy.sh` and by adding the missing completion data
> Fixes build failure in the default npm run start flow

- src/components/ImageView/ImageView.js
Hi!
We've got this project where we need to detect lots of small objects in a photo. We discovered Label Studio to be a great tool, with one downside: you can't pan the image while it's zoomed. We use zoom all the time and constantly zooming in and out is really unproductive. So I've added an ability to pan the image along with its polygons. When image is zoomed, it can be panned with Shift + Left mouse button, or with middle mouse button.
> Added an ability to pan image when zoomed

- examples/image_bbox/config.xml
- examples/image_ellipses/config.xml
- src/mixins/SelectedModel.js
- src/regions/EllipseRegion.js
- src/regions/RectRegion.js
- src/tags/control/Ellipse.js
- src/tags/control/EllipseLabels.js
- src/tags/control/Label.js
- src/tools/Ellipse.js
- src/tools/Rect.js
- src/utils/colors.js
In accordance with my suggestion #30 I made this pull request.
I have successfully implemented this functionality for `RectangleLabels` and `EllipseLabels`. Fill with color for `PolygonLabels` seems to be different. So I decided to not implement it right now. Maybe a little bit later.
> fillOpacity parameter

- src/tags/object/HyperText.js
- src/tags/object/Text.js
Both for Text and HyperText leave the text selection untouched if there are no labels selected at this moment. This allows user to copy selected text.
Previously text selection was cleared immediately after mouse up, preventing user to interact with text.
Fixes heartexlabs/label-studio#265
> Don't clear selection when no labels active

- src/env/development.js
- src/tags/object/Text.js
* Don't break on some selections (possibly reaching the end of block)
* Always show selected text in regions list and in serialisation (sometimes it was blank)
> Fix work with ranges for word granularity

- src/index.js
- src/stores/SettingsStore.js
On some sandboxed environments any access to such properties causes exception.
Settings can work with defaults and store data per session.
Service Workers aren't used anyway.
> localStorage and serviceWorker break sandboxed env

- src/tags/object/HyperText.js
Allow links to be clickable to open resources from HTML document.
> Add clickableLinks param to HyperText

- src/components/RelationsOverlay/BoundingBox.js
- src/regions/Area.js
It was impossible to create relations between `BrushRegion` and any other region.
This PR resolves this issue.
> Fix BrushRegion relations creation

- src/env/development.js
- src/tags/object/TimeSeries.js
- src/tags/object/TimeSeries/Channel.js
On: don't scale y axis at all, always fit for all the values on channel
Off: scale to fit currently displayed data
Can be changed globally for TimeSeries and locally on Channel
> Add `fixedScale` param to TimeSeries, default off

- e2e/tests/helpers.js
- e2e/tests/image.toggle-visibility.test.js
- src/components/Entities/Entities.js
- src/components/Entities/Entities.module.scss
- src/components/Relations/Relations.js
- src/stores/RegionStore.js
This pull request should add buttons for hiding and showing groups of regions. 
- Hide / show all regions.
- Hide / show some regions grouped by their label (in case of using "labels" view for region tree)
> Switching visibility for all regions at once

- src/tags/control/Brush.js
- src/tags/control/Ellipse.js
- src/tags/control/KeyPoint.js
- src/tags/control/Labels/Labels.js
- src/tags/control/Pairwise.js
- src/tags/control/Polygon.js
- src/tags/control/Rectangle.js
@hlomzik please check that I added this correctly and didn't miss any tags or defaults.
Also, I added docs for the Brush tag since that is supported independently.
- Added docs for the Brush tag
- Added the "smart" and "smartOnly" parameters to Brush, Ellipse, KeyPoint, Polygon, Rectangle tags
- Update the Pairwise tag with additional details (separate from smart tags).
> Add smart tags

- src/tags/visual/Table.js
it's actually an object tag, so should behave and inherit appropriately
> fix: DEV-1471: Table tag breaks View All

- src/stores/AnnotationStore.js
- src/tags/object/RichText/view.js
- src/utils/selection-tools.js
- this causes draft creation in 5 sec after task loaded
- if there was a draft undo would switch to original task state
- if there was no drafts undo would not change anything
- try to create region in a text after emoji — it will be shifted
- reload page — it'll be shifted more
> fix: DEV-1220: fix HTML misplacements

- src/stores/AnnotationStore.js
- src/utils/feature-flags.js
it may not help, but can break UX because it unselects region/label
also change CRLF to LF in feature-flags.js
> fix: DEV-1555: move setSuggestions fix under FF

- e2e/fragments/AtRichText.js
- e2e/helpers/Selection.js
- e2e/tests/regression-tests/richtext.test.js
- src/components/Entities/Entities.scss
- src/stores/SettingsStore.js
- src/tags/object/RichText/RichText.styl
- src/tags/object/RichText/view.js
Show them again if such setting enabled.
Uses `data-linenumbers` attribute to store current setting.
Also fix region items appearance in sidebar list.
> fix: DEV-23: show line numbers again for Text

- src/tags/control/Number.js
There are no results if user didn't touch Number,
but if there is defaultValue we should create a new result
with it on the fly for every region.
That works only for required perRegion Number with no value added.
> fix: DEV-2120: required Number with default value

- src/mixins/HighlightMixin.js
- src/tags/object/RichText/view.js
- src/utils/html.js
1. highest priority for LSF spans' styles, so page styles won't affect them
2. `<a>` without `href` should not be disabled
> fix: DEV-1760: styles override for spans and links

- src/utils/feature-flags.ts
- src/utils/selection-tools.js
When `start` is on the last char or `end` is on the first char
of text node, find better to fit to have first char for `start`
or last char for `end`.
> fix: DEV-2480: convenient text region offsets

- src/common/Space/Space.styl
- src/common/Space/Space.tsx
- src/components/CurrentEntity/AnnotationHistory.styl
- src/components/CurrentEntity/AnnotationHistory.tsx
Fixes the annotation history item spacing between the user name and timestamp, truncating user names which would cause the container to overflow.
> fix: DEV-2364: Annotation history name/timestamp spacing improvement

- src/components/Timeline/Views/Wave/Wave.tsx
Null block loading a wave-surfer instance that does not have a value
> fix: DEV-2269: Wave surfer preview crash fix

- src/components/Taxonomy/Taxonomy.module.scss
- src/components/Taxonomy/Taxonomy.tsx
- src/components/TreeStructure/TreeStructure.tsx
- src/tags/control/Taxonomy.js
In order to support text without spaces that exceed the maximum width for taxonomy, creation of an invisible taxonomy item to check its width and calculate how many lines was necessary per item. Additionally I added the missing visibility mixin check.
> fix: DEV-1975: DEV-1843: Support long unbroken taxonomy line breaks

- src/hooks/useRegionColor.ts
- src/regions/KeyPointRegion.js
They shouldn't grow when user zoom in
Also don't change keypoint size on select —
previously selected and highlighted keypoint had strokeWidth=2
> fix: DEV-2577: keep keypoints the same size

- src/regions/PolygonPoint.js
- src/utils/feature-flags.ts
Delete points with an alt/opt click, behind `ff_front_dev_2431_delete_polygon_points_080622_short`
> feat: DEV-2431: Alt click deletes polygon points

- src/utils/utilities.ts
we were getting an array instead of a string, which caused a js error that prevents the page from working correctly.
solution: I now check if `str` is actually a string before continuing
> fix: DEV-2465: Paragraphs data is not loading to QuickView

- src/tags/object/TimeSeries/Channel.js
resolving this issue by hiding the handles. would've preferred a more event driven solution, but i couldnt find a spot for that - it looks like we're leveraging d3 functionality
> fix: DEV-2367: User is able to edit Time Series results imported as read-only

- src/mixins/DrawingTool.js
this corrects an issue where the region flickers while dragging out a rectangle when using 3 point bbox feature
> fix: DEV-2592: Bounding box is flickering during region creation

- src/components/SidePanels/DetailsPanel/DetailsPanel.tsx
- src/stores/Annotation/store.js
The selectAnnotation has a side effect of downstream wiping out the history. On the initial page data setup, it needs to retain the history it fetched.
> fix: DEV-2437: Retain history on initial load of annotation review stream

- src/mixins/DrawingTool.js
resolving an issue where 3 point rectangles were drawing before selecting a different tool even after removing them as an option from labeling settings
> fix: DEV-2696: 3point bbox tool remains selected but hidden, when user changes label configuration from Rectangle to RectangleLabels

- src/components/Toolbar/FlyoutMenu.styl
minor correction for a fly out menu item positioning incorrectly on smaller screens (smaller than 1200px wide)
> fix: DEV-3049: visual bug with the Zoom To flyout menu on smaller screen sizes

- src/components/VideoCanvas/VideoCanvas.tsx
- src/hooks/useUpdateEffect.ts
Added a new hook and reduced renders a bit, there are still a lot of extra renders
Clear timeout on every call to check loaded (there are always at least two) 
If video is not loaded in 3 seconds about load display error message and reset spinner
> fix: DEV-3284: If video load times out display error message

- src/regions/RectRegion.js
Validation added on serialization to validate if stage is ready to not convert px to percent if it's not necessary.
> fix: DEV-3607: Add validation if stage is ready

- src/tags/object/TimeSeries/Channel.js
null block right value beyond slices range
> fix: DEV-3645: Timeseries brush to end of timeline error

- src/mixins/HighlightMixin.js
`document` and `styleTag.sheet` might point to working iframe, not a visible one, so we need to re-reference them during changes from correct `styleTag`
> fix: DEV-3490: Change color when user changes label

- src/components/App/App.styl
This reverts commit 8b45238a98180f3358876043425772f53510cc52.
> fix: DEV-3901: Paragraph overflow text issue when outliner disabled (revert)

- src/tags/control/TextArea/TextArea.js
Disable TextArea Add button with showSubmitButton=false.
Now this parameter is true by default because previously it had no effect and true should not do anything actually, but false forces button to disappear.
> fix: DEV-3892: Get showSubmitButton=false to work

- src/lib/AudioUltra/Common/Worker/index.ts
- src/lib/AudioUltra/Controls/Player.ts
- src/lib/AudioUltra/Media/ChannelData.ts
- src/lib/AudioUltra/Media/MediaLoader.ts
- src/lib/AudioUltra/Media/WaveformAudio.ts
- src/lib/AudioUltra/Regions/Regions.ts
- src/lib/AudioUltra/Regions/Segment.ts
- src/lib/AudioUltra/Visual/Visualizer.ts
- src/lib/AudioUltra/Waveform.ts
This PR improves destructor behaviour amongst Audio classes. This is to enable a more stable usage of the async nature of the audio loading, processing.
There is an overall issue with working with the WebAudio api that can produce issues of crashing the browser, and no clear way to resolve it.
So in the meantime it is guarded all over and attempted to cleanup with as forceful efforts that can be done, and it is promise chained against the MediaLoader instance to try and stop the race condition and browser crashes that come with `decodeAudioData` getting run multiple times. This improves the usability, but crashes are still possible just much more unlikely.
As it is right now, we are already closing and removing contexts so there is not much more that can be done at this time. The crashes …
> fix: DEV-3990: Cleanup worker and audio contexts

- src/tags/control/KeyPointLabels.js
They use colors from `background` property from respective `Label`
> docs: Remove useless color params in KeyPointLabels

- src/components/App/App.styl
Preview is good because it uses bottomSidePanel settings, but small screens use previous grid layout.
> fix: DEV-3919: Outliner on a narrow screen

- e2e/tests/audio.test.js
- src/core/settings/keymap.json
- src/tags/object/AudioUltra/view.tsx
If a gray segment is created accidentally, it's impossible to remove it by pressing the delete button. It's creating some confusing while user is annotating
User can delete a gray segment by pressing the delete button
User can delete a gray segment just by pressing backspace button
None
no
no
none
> fix: LSDV-4541: Audio segment is being deleted by pressing delete button

- e2e/tests/image.magic-wand.test.js
- src/core/Registry.ts
- src/tags/control/MagicWand.js
MagicWand model is incompatible with new version of ControlBase tag and crashes the app. So we can just remove `name` param as it's defined in base tag.
Application crashes on load with FF for DEV-3391 on.
The reason is the `name` param defined in `MagicWand` model
and it's clashed with `name` definition in `ControlBase`.
Removes `MagicWand#name` param because it's already defined
It fixes breaking change.
View All, Magic Wand, mst models
> fix: LSDV-4627: App crash with FF for DEV-3391 is on

- src/stores/Annotation/Annotation.js
- src/utils/feature-flags.ts
The problem with saving a draft with empty results affects the functionality of comments.
This allows saving drafts with empty results. So that there should not be a problem with adding comments caused by this issue. And by this we also avoid draft saving permanent state. 
We can save a draft with empty results. But this solve the issue.
Currently saving a draft with empty results gets and this causes adding comments functionality to hang.
N/A
Nope
Nope
We also can rollback saving a draft if we can't save it. But this will create an ugly artifact in the UI and adding comments will still save an empty draft.
`fflag_fix_font_lsdv_3009_draft_saving_stuck_130223_short`
`Annotation History`, `Autosave`, `Draft`, `Comments`
> fix: LSDV-3009: Fix draft saving stuck

- e2e/tests/audio/audio-webaudio-decoder.test.js
- src/lib/AudioUltra/Media/AudioDecoder.ts
- src/lib/AudioUltra/Media/AudioDecoderPool.ts
- src/lib/AudioUltra/Media/BaseAudioDecoder.ts
- src/lib/AudioUltra/Media/MediaLoader.ts
- src/lib/AudioUltra/Media/WaveformAudio.ts
- src/lib/AudioUltra/Media/WebAudioDecoder.ts
- src/lib/AudioUltra/Waveform.ts
- src/tags/object/AudioUltra/model.js
- src/tags/object/AudioUltra/view.tsx
- src/utils/feature-flags.ts
To support more options for audio data decoding, which allows different support levels for formats (webaudio api follows strictly browser formats, where ffmpeg wasm is based on the included compiled codecs). This helps to give more flexibility to meet the needs of the labelling projects, for example. Video Timeline segmentation of webm files. That would require switching the audio tag to this `webaudio` decoder option to meet that need as the included ffmpeg wasm decoder currently does not support that format. But for larger duration audio, it is more stable to use the `ffmpeg` decoder. This way we can quickly support more use cases, without having to compromise the UI/UX, or reverting/pointing users to Audio v1 which would be lacking many core features that we …
> feat: LSDV-4701: Audio v3 webaudio alternative decoder option

- src/components/VideoCanvas/VirtualVideo.tsx
An issue occurs when a user is using presigned urls to load Video. This is a result of presigned urls being specific to a particular method, which is `GET` in this case. Previously we were using `HEAD` requests to check content type header to ensure playback was possible, so that we could early report issues back to the user. This ends up producing a false positive since the `HEAD` requests will fail on any presigned urls, but would otherwise allow the video to load because the url was still valid, but only valid to `GET`.
Uses an empty `Range: bytes=0-0` header `GET` request to the file, mimicking a `HEAD` request in that we will not request data but receive the metadata we would otherwise require. This will then succeed and not trigger invalid file format errors …
> fix: LSDV-4662: Use empty range GET requests instead of HEAD to avoid CORS issue on video presigned urls

- src/lib/AudioUltra/Media/MediaLoader.ts
When requesting urls for audio, it sometimes produces a CORS error after which it doesn't resolve and remains in error until the browser cache is cleared.
There is a problem with when the browser requests Partial Content for media based requests, having a completely different Header response than a full content Get request that is made. This eventually leads to the Partial Content request getting cached in the browser, and when trying to issue a Get request to that same url produces a CORS error. 
This fix just puts a small query param added to **only** the Get requests made for the waveform data. It is small and deterministic purposefully so we don't ruin cache which would cause many more issues. This allows a differentiation between the Get requests made for …
> fix: LSDV-4593: CORS error requesting audio

- src/components/ImageView/ImageView.js
- src/mixins/DrawingTool.js
- src/tools/Brush.js
LSDV-4774
Fixes an issue when it's possible to start a Brush/Polygon region on one image and continue drawing on a different image.
Regions created with Brush or Polygon will stay on the image they were initially created on. The user can continue drawing a region if they return to the image where they started. Otherwise, any drawings are ignored.
If a user creates an unfinished Polygon and switches to the next image, the Polygon will travel to the next image as well. Whenever the Polygon is finished, it will stay on the last selected image.
If a user creates a Bush region, switches to the next image, and starts drawing, they won't see anything. As soon as they switch back to the previous image, they will see everything they drew on the second image. Effectively, …
> fix: LSDV-4774: Drawing on the hidden image in MIG scenario

- e2e/fragments/AtImageView.js
- e2e/tests/image-list.test.js
```
MIG
No errors during brush export in MIG:
3 == 2
+ expected - actual
-3
+2
```
`Ctrl`+`d` is used for duplicating selected region and going to the next page in the same time.
The test isn't failing every time, cause it can have enought time to use the hotkey before the brush region is created.
It solve hotleys duplicating problem in test. 
tests
> test: LSDV-4943: Fix MIG Brush test

- src/components/SidePanels/OutlinerPanel/ViewControls.styl
- src/components/SidePanels/OutlinerPanel/ViewControls.tsx
with manual grouping the text is too long and pushes the filter off of the visible area of the default width of panels 
this change shortens the text of sort to allow for the filter to be visible 
filter is visible 
it is not visible 
N/A
N/A
N/A
N/A
N/A
bug fix frontend new ui
> fix: LSDV-4953: Filter cut off at default panel width

- src/stores/AppStore.js
- src/utils/feature-flags.ts
Shared store do not work with dynamic children of Taxonomy. Taxonomy does not update its children between different tasks.
This fix reset shared storage on task switching to prevent stucking irrelevant dynamic children
Maybe...
N/A
The other approach is moving stories to the annotation level.
It's much harder to do, and does not seem necessary.
`fflag_fix_front_lsdv_4998_missed_dynamic_children_030523_short`
`Taxonomy`, `Dynamic Children`
> fix: LSDV-4998: Fix missed dynamic children on task switch

- src/components/AnnotationsCarousel/AnnotationsCarousel.tsx
when new annotations are saved they moved from the front to the end of the list 
this sorts the annotations by creation date 
the annotations are saved in the order they are created 
when a new annotation is a draft it is in the front of the list and moves to the end when submitted 
N/A
N/A
N/A
N/A
N/A
annotations carousel
> fix: LSDV-4960: Sort annotations by creation date instead of pk

- src/common/Tooltip/Tooltip.tsx
- src/components/Taxonomy/Taxonomy.tsx
- src/tags/control/Choice.js
- src/tags/control/Choices.js
- src/tags/control/Taxonomy/Taxonomy.js
- src/utils/feature-flags.ts
- tests/functional/data/control_tags/choice.ts
- tests/functional/data/control_tags/taxonomy.ts
- tests/functional/feature-flags.ts
- tests/functional/package.json
- tests/functional/specs/control_tags/choice.cy.ts
- tests/functional/specs/control_tags/taxonomy.cy.ts
- tests/functional/yarn.lock
We have this functionality for `<Label/>` tag and it would be fair to add to choices too.
A new `hint` parameter for `<Choice/>` allows to add informative hints in form of tooltips for each `Choice` element in each containers' mode.
`@heartexlabs/ls-test`
N/A
N/A
N/A
`fflag_feat_front_prod_309_choice_hint_080523_short`
`Choice`, `Choices`, `Taxonomy`, `Tooltip`
> feat: PROD-309: Add hint for Choice

- src/components/SidePanels/OutlinerPanel/OutlinerPanel.tsx
- src/components/SidePanels/OutlinerPanel/ViewControls.tsx
- src/components/TopBar/Controls.js
- tests/functional/specs/outliner/filter.cy.ts
The message that show how many itens are hidden was being shown even when there were no items hidden
Now the message is being shown just when there are some items hidden.
no
na
fflag_feat_front_lsdv_3025_outliner_filter_short
> fix: LSDV-5090: Hidden regions notifications is displaying when filter is applied

- src/components/CurrentEntity/GroundTruth.js
- src/components/CurrentEntity/GroundTruth.styl
The icon of the Set as ground truth button is gray when it is enabled, which makes it look disabled.
The icon is set to dark to seems to be enabled
NA
no
no
NA
NA
> fix: LSDV-5116: Change ground truth color to dark

- tests/functional/package.json
There is a problem with stale libraries in internal dependencies of cypress wich causes tests failures in some cases. Forcing of usage of more fresh version should solve this problem.
> fix: Fix the problem with combineCoverage and coverageReport tasks in cypress tests

- src/components/Comments/CommentForm.tsx
- src/components/TopBar/CurrentTask.js
The postpone button was disabling when user switches between the tabs in side panels
Change the way the comment in this session is checked
> fix: LSDV-5136: Navigate between tabs in the side panels is not reseting the comments

- e2e/tests/regression-tests/annotation-button.test.js
- src/components/AnnotationsCarousel/AnnotationButton.styl
Annotation tabs shift when hovered
It fixes border width of hovered annotation tab.
`fflag_feat_front_dev_3873_labeling_ui_improvements_short`
`AnnotationButton`
> fix: LSDV-5162: Fix shifting of annotation tabs on hover

- src/components/AnnotationsCarousel/AnnotationButton.tsx
- src/stores/Annotation/store.js
When deleting an annotation, which was the source of a duplicate, any updates or submissions of this duplicate annotation would cause an error because the original was already deleted.
Clear any parent annotations connected to the deleted annotation, to ensure the proper submission handling takes place and does not throw errors when updating or submitting this data.
Annotation Duplication/Deletion/Submission
> fix: LSDV-5148: Runtime error when user tries to update/submit duplicated annotation while original is already deleted

- src/components/SidePanels/OutlinerPanel/TreeView.styl
New UI RegionItem labels were getting pushed by the controls width taking up all the available space. These should be left to flex to distribute space and create this separation.
RegionsPanel
> fix: LSDV-5214: Multi-word labels containing spaces in regions list are broken down into multiple rows on every space character

- src/components/AnnotationsCarousel/AnnotationButton.tsx
Currently predictions cannot be deleted, so there is no point in having a delete button. Removing this for consistency until such time that we have a proper method of deleting predictions.
AnnotationButton
> fix: LSDV-5158: Hide prediction delete button as it doesn't actually allow prediction deletions at this time

- src/stores/Annotation/Annotation.js
- src/stores/AppStore.js
Draft is not saved on postpone, only prediction is drafted if it was the source for annotation. Fixed.
Draft is not saved on postpone, only prediction is drafted if it was the source for annotation.
Save draft on postpone and wait for it.
Save draft on postpone and wait for it.
Postpone just saves result as draft, but that's only the case when annotation was created from prediction, in all other cases latest changes are lost.
none
Postpone will wait for draft saving, so this can add some time, but draft is saved in "fast" way.
nope
Draft should be saved anyway, so this could just be different from technical perspective. We could call `autosave.flush()`, but this will not save draft if drafts are paused, which is not good I think. …
> fix: LSDV-5262: Save draft on postpone

- src/components/AnnotationsCarousel/AnnotationButton.tsx
Duplication of annotations should follow the same logic as creation, and only be available if the capability is set. This logic diverged a bit, which will cause bugs with upstream usages of LSF.
Only show the duplication button for annotations, if the AnnotationTab has the capability to create a new annotation.
AnnotationTab
> fix: LSDV-5259: Duplication of annotations can only happen if creation is allowed.

- e2e/tests/audio/audio-regions.test.js
- src/lib/AudioUltra/Regions/Regions.ts
- src/lib/AudioUltra/Regions/Segment.ts
- src/regions/AudioRegion/AudioUltraRegionModel.js
When interacting with the Audio regions, it was only considering the layered indices in order of when the region was created. This leads to lack of context and ability to freely work with overlapping regions efficiently.
Anytime a region is selected from within the audio interface or the regions sidepanel, bring the region to front of the list so that it can be easily dragged or resized without having to hide overlapping regions or move out the obscured region.
Audio
> fix: LSDV-5260: Selected region can not be moved / resized when it's under another region

- src/components/SidePanels/TabPanels/SideTabsPanels.tsx
- src/components/SidePanels/TabPanels/__tests__/utils.test.tsx
- src/components/SidePanels/TabPanels/utils.ts
Panels with tabs were not saving collapsed state 
This saves the collapsed state of side panels 
Now local-storage will consistently preserve collapsed state and repopulate into app state 
side panels collapsed states are not saved
N/A
no
no
we could have used a separate storage item but opted instead to lump with panel data so that we can check that the two match upon retrieval
n/a
sidepanels
> fix: LSDV-5314: Persist collapse panel state

- src/hooks/useRegionsCopyPaste.ts
Handle Cmd+X in the same way as Cmd+C and Cmd+V in regions copypasting code, so in Config Editor Cmd+X would not be overtaken by mistake.
Cmd+X does nothing in Config Editor
Doesn't prevent Cmd+X from usual execution when it's in CodeMirror editor.
none
nope
nope
it just makes it in sync with copy and paste handlers, so no alternatives
none
Config Editor
> fix: LSDV-5316: Fix Ctrl/Cmd+X in Config Editor 

- .github/actions/download-artifact/action.yml
- .github/actions/upload-artifact/action.yml
- .github/workflows/build_bundle.yml
- .github/workflows/e2e_tests.yml
- .github/workflows/fun_tests.yml
- .github/workflows/tests_coverage.yml
- .github/workflows/unit_tests.yml
There were cases that the handling of files through the general github actions upload/download artifact would create a massive overhead requiring to call the api for every single file individually. This along with some large file counts creating > 30 minute archive upload runs 🤯. This is a massive waste of resources and holds up pipeline times.
This changes the used github actions for upload/download archive to tar on upload and send a single file (much more efficient given the way the upload works with chunked + resumable uploads). Conversely all download-artifact calls untar the file in the same manner. The only difference here is that we no longer have to specify paths on the download as the directory structure is captured in the upload tar.
> chore: CI test artifact handling improvement

- src/stores/AppStore.js
- src/utils/feature-flags.ts
This feature may be disabled in future.
And it definitely stops us from using very dynamic ML responses. For example choices may have problems with manual accept.
Choices not always appears after manual accept
Auto accept any ML backend response with FF on
none
nope
nope
fix desired tags ad-hoc, but that's harder and makes less sense.
`fflag_feat_all_lsdv_e_294_llm_annotations_180723_long`
LLM, textarea, choices
> fix: LSDV-5400: Auto accept all annotations

- src/tags/control/Label.js
Changes in #1460 caused a regression with non region label handling, ie. text ranges. Small adjustment to just look at the result type again.
Labels
> fix: LSDV-5409: Existing text range cannot be changed into a different label

- e2e/tests/sync/audio-paragraphs.test.js
- src/tags/object/Paragraphs/AuthorFilter.js
- src/tags/object/Paragraphs/HtxParagraphs.js
- src/tags/object/Paragraphs/Paragraphs.module.scss
- src/tags/object/Paragraphs/Phrases.js
- src/tags/object/Paragraphs/__tests__/Phrases.test.tsx
- src/tags/object/Paragraphs/model.js
If user scrolls the container and the current playing Paragraph is outside the screen the automatically scroll will stop work and it will start working back if user returns the focus to the current playing Paragraph
If the automatically scroll is turned on, the Paragraphs will scroll to the current paragraph every time its change, doesn't matter if the current Paragraph is in focus or not
no
no
no
NA
fflag_feat_front_lsdv_e_278_continuous_scrolling_of_paragraph_segments_with_audio
> fix: LSDV-5256: Stop automatically scrolling if current Paragraph is not on the screen

- src/tags/object/Paragraphs/model.js
Paragraph wasn't sync with audio without the contextual scrolling FF turned on, also the audio was auto pausing after change the paragraph that is being played
Paragraph and audio is sync and paragraph doesn't pause automatically when active paragraph changes anymore
> fix: LSDV-5460: Paragraph is sync with audio and isn't automatically pausing anymore

- src/tags/object/RichText/domManager.ts
- tests/functional/package.json
- tests/functional/yarn.lock
The fix https://github.com/HumanSignal/label-studio-frontend/pull/1516 broke RichText functionality under the flag `fflag_feat_front_lsdv_4620_richtext_opimization_060423_short`.
This PR should fix it.
N/A
Nope
Nope
N/A
`fflag_feat_front_lsdv_4620_richtext_opimization_060423_short`
`RichText`
> fix: LSDV-5544: Fix RichText tag in non-Chromium browsers

- src/components/NewTaxonomy/NewTaxonomy.tsx
- src/tags/control/Taxonomy/Taxonomy.js
- submitted values displayed after load with 5452 FF on
- per-region values are displayed with 5452 FF on
- fix API root item: object with `items` instead of plain array of items
- support `leafsOnly` param
Critical issues
Problems appeared only with `fflag_feat_front_lsdv_5452_taxonomy_labeling_110823_short` on
Async Taxonomy, Taxonomy Labeling
> fix: LEAP-14: Fixes for New Taxonomy

- src/stores/SettingsStore.js
The labeling interface settings wasn't keeping after user changes page, all storages are being destroyed on AppStore when user leaves the Annotation Engine and when SettingsStore is destroyed, it's triggering onSnapshot method, and changing the saved config on the localStorage with the default variables on the store.
The fix is validating if store is being destroyed and if it's being destroyed it's avoid that localStorage is set with the default values from the store …
> fix: LSDV-5487: Keep the labeling interface settings after change page

- src/components/BottomBar/Controls.js
- src/components/BottomBar/Controls.styl
- src/utils/feature-flags.ts
An option submit/update and exit the stream to stop lead time from running on
feature
you are able to submit and not load another task and instead return to the datamanager list
if you want to take a break you would have to close the window
N/A
no
no
There are likely numerous methods for passing information to the LSF SDK. However, since we were already utilizing query parameters in the 'submit' function, it made sense to continue using this approach for passing a temporary flag to the SDK. This method is convenient because it avoids interfering with the existing chain of functions that have been scaffolded between the two stores.
fflag_feat_front_prod_e_111_annotator_workflow_control_short
_(for bug fixes/features, be …
> feat: OPTIC-3: Enable users to submit and pause their lead time by returning to the dm list 

- src/components/InstructionsModal/InstructionsModal.tsx
- src/components/InstructionsModal/__tests__/InstructionsModal.test.tsx
Format instructions as HTML the same way we do it in LS/LSE
Discrepancy between Label Stream behavior, where instructions displayed in intro modal, formatted as HTML, and instructions modal opened by (i) button, where all HTML displayed as plain text.
Formats instruction as HTML
It dangerously displays instructions as HTML, this can use any scripts etc. But the same is used already in LS/LSE. And this instruction can be set only by managers.
This exact task made as it should be. But we can add some layer of security, sandboxing the modal.
Instructions, Label Stream
> fix: LSDV-5547: Support HTML in Instructions modal

- src/components/BottomBar/Controls.js
- src/stores/Annotation/Annotation.js
- src/stores/AppStore.js
- tests/functional/package.json
- tests/functional/yarn.lock
To help keep more control with the annotator's workflow we are going to be offering more aggressive draft saving, and notification of this. However it was identified that this would have introduced a regression with regards to creating a blank draft in doing so, and thus this fix is required to allow this functionality to be enabled in full.
- `fflag_feat_optic_2_ensure_draft_saved_short`
LabelStream, QuickView
> fix: OPTIC-109: Blank draft should not be created when an annotation is submitted

- src/core/Hotkey.ts
- tests/functional/data/image_segmentation/tools/zoom.ts
- tests/functional/package.json
- tests/functional/specs/image_segmentation/tools/zoom.cy.ts
- tests/functional/yarn.lock
`ctrl+plus` and `ctrl-minus` hotkeys do not work for zoom in Image Segmentation.
It adds aliases for `plus` and `minus` comands to make it work with original keymaster.
`@heartexlabs/ls-test`
Nope
Nope
Forking and changing `keymaster`
N/A
`Hotkeys`, `Image Tools`
> fix: LSDV-5560: Fix plus and minus hotkeys

- src/stores/AppStore.js
When using CTRL+ENTER and using the new draft saving mechanisms to ensure drafts are reliably saved, it would create a blank draft incorrectly.
Hotkeys, Annotation Submit
> fix: OPTIC-133: Blank draft submitted with annotation when using hotkey submit

- .github/workflows/e2e_tests.yml
- src/tags/control/Taxonomy/Taxonomy.js
The app is not using the default message error box, It's showing a modal box blocking all the UI when it shows
It's being changed the way that the error is being shown from the modal box that is blocking the UI to the default message error box in red that hide the tags and just show the error detailed.
none
no
no
no
fflag_feat_front_lsdv_5451_async_taxonomy_110823_short
> fix: LEAP-252: Use standard error message for Async Taxonomy errors

- src/components/NewTaxonomy/NewTaxonomy.tsx
- src/tags/control/Taxonomy/Taxonomy.js
- tests/functional/data/control_tags/taxonomy.ts
- tests/functional/specs/control_tags/taxonomy.cy.ts
Cache both alias and value for selected items in Taxonomy. This leads to couple of fixes and improvements:
- correct showFullPath
- faster visibility checks
- tidy code
`selected` is managed only in Taxonomy.js in `onChange()` and `needsUpdate()` methods, then used mostly to detect its length, and to pass to Taxonomy component (new or old).
Full selected items depend on list of selected values and list of already loaded items.
_(briefly …
> feat: LEAP-235: Use selected items with full info

- src/tags/control/Taxonomy/Taxonomy.js
A lot of things was changed in New Taxonomy, so some slight regression is possible in some cases, so some clients may want to use the old one.
Include the 'legacy' property in the 'Taxonomy' tag, allowing users to access the legacy version, even when the feature flag is enabled.
no
no
no
no
fflag_feat_front_lsdv_5451_async_taxonomy_110823_short
> fix: LEAP-256: Include the 'legacy' property in the 'Taxonomy' tag

- e2e/package.json
- e2e/yarn.lock
- package.json
- tests/functional/package.json
- tests/functional/specs/audio/audio_paragraphs.cy.ts
- tests/functional/yarn.lock
- yarn.lock
security vulnerabilities that must be fixed
It's updating packages from root, test and e2e to fix security vulnerabilities
> fix: LEAP-306: Fix security vulnerabilities

- src/components/ErrorMessage/ErrorMessage.module.scss
Create Project modal's preview had broken styles
Overrides styles from LS modal (it has `white-space: pre-wrap` for some reason)
> fix: LEAP-295: Fix error styles in LS modals

- .github/workflows/e2e_tests.yml
- src/tags/control/Taxonomy/Taxonomy.js
- src/tags/control/Taxonomy/Taxonomy.styl
- tests/functional/package.json
- tests/functional/yarn.lock
We combine two things:
- flag we already have inside taxonomy (`loading`)
- spinner we already use for old taxonomy
and display spinner when flag is true.
Also styles should be adjusted to match the height of taxonomy to not jump when it's loaded.
Currently taxonomy displays No Data dropdown stub while loading. And this loading state is not indicated anyhow, confusing the user.
To modify current empty state to change phrasing. But spinner is more clear and we already have it.
The downside is that selected items are only visible after taxonomy is loaded.
`fflag_feat_front_lsdv_5451_async_taxonomy_110823_short`
Taxonomy
> fix: LEAP-299: Show spinner while taxonomy's loading

- src/common/Dropdown/DropdownComponent.tsx
- src/components/BottomBar/Controls.js
- src/components/BottomBar/Controls.styl
Look of submit and exit should match figma  
> fix: OPTIC-142: Submit and exit style update

- src/components/Ranker/Column.tsx
- src/components/Ranker/Item.tsx
- src/components/Ranker/Ranker.module.scss
- src/components/Ranker/Ranker.tsx
- src/tags/control/Ranker.js
Allow to collapse and expand cards for easy interactions. With collapsed cards user can see lot of items together with makes rearrangement easier.
Collapsed/expanded states are indicated by ASCII triangles (△/▽ and ▲/▼ for hovered state) used in css to change only class names, not the content and to keep indicators in one place.
Collapse is desirable action so column is treated as expanded when at least one item is expanded. This allows to collapse all items in any state by one click.
New hidden parameter added to `Ranker`: `collapsible` with default true to allow to disable this functionality if it's not needed for any reason.
none
nope
nope
Cards can be made hidden with animation to not change the content inside, but this will require calculations of their height.
none yet
_(check all …
> feat: LEAP-336: Collapsible cards in Ranker

- src/tags/control/Taxonomy/Taxonomy.js
- Update apiUrl param description
- Add links to Taxonomy template page
- Add disclaimer about including the path separator in data
- Include regions in maxUsages param
> docs: DOC-121: Update Taxonomy tag page for external taxonomy

- src/components/ImageView/ImageView.js
- tests/functional/data/image_segmentation/crosshair.ts
- tests/functional/package.json
- tests/functional/specs/image_segmentation/crosshair.cy.ts
- tests/functional/yarn.lock
The crosshair parameter was broken,
`ls-test`
Nope
Nope
N/A
'fflag_fix_front_leap_32_zoom_perf_190923_short'
`Image`
> fix: LEAP-364: Fix crosshair functionality

- .github/workflows/fun_tests.yml
ls-frontend-test is public now, so it doesn't require any auth.
We need to unblock all external PRs. Currently Cypress step requires SSH credentials to get access to former private ls-frontend-test repo, but it's public already!
> ci: LEAP-296: Remove SSH Agent from Cypress step

- src/regions/PolygonRegion.js
- src/tags/control/Taxonomy/Taxonomy.js
While drawing a polygon user can move already added points. However those points did not move lines connected to them, creating visual glitch. Actual point coords were correct.
The problem is that lines have memoization for their coords, based on point objects.
But when any of two points was moved this was not changed the object and was not triggering re-render of the line.
> fix: LEAP-377: Polygon points can be moved correctly

- e2e/tests/regression-tests/image-ctrl-drawing.test.js
- src/regions/BrushRegion.js
- src/tags/object/Image/Image.js
- src/tools/Base.js
- src/tools/Brush.js
- src/tools/Erase.js
- src/tools/MagicWand.js
- src/tools/Zoom.js
- tests/functional/data/image_segmentation/tools/brush.ts
- tests/functional/data/image_segmentation/tools/magic-wand.ts
- tests/functional/package.json
- tests/functional/specs/image_segmentation/tools/brush.cy.ts
- tests/functional/specs/image_segmentation/tools/magic-wand.cy.ts
- tests/functional/yarn.lock
Fixes after https://github.com/HumanSignal/label-studio-frontend/pull/1565 for LEAP-32
- an issue with wrong position of brush stroke highlighted on hover. 
- an issue with clipping brush strokes by image boundaries.
- an issue with drawing and erasing over existing brush regions.
`@heartexlabs/ls-test`
Nope
Nope
N/A
`fflag_fix_front_leap_32_zoom_perf_190923_short`
`Brush`, `Magic wand`, `Image Segmentation`
> fix: LEAP-419: Fix brush issues appeared after fixing zoom performance

- src/components/RelationsOverlay/NodesConnector.js
In the case of Image Segmentation with Image tag being in gallery mode a relation arrow may not follow the regions on switching between images.
It adds an directive for relation to observe current image index to initiate rendering of an arrow on switching between images.
N/A
Nope
Nope
N/A
N/A
`Image Segmentation`, `Image`, `Relations`, `Gallery`
> fix: LEAP-89: Fix rendering of relation arrow in MIG case

- src/components/BottomBar/Controls.styl
- src/components/Comments/CommentForm.styl
- src/components/SidePanels/TabPanels/PanelTabsBase.styl
- src/components/TopBar/Controls.styl
In the movement to MonoRepo, there were some observed idiosyncrasies in the css build output. After looking further into why, it appeared there were some incorrect syntax being used previously that our old builds were tolerant to, however newer libraries no longer allow this and the output css had incorrect or missing values as a result causing minor issues in the UI. This just fixes the upstream issues so it can be corrected for the monorepo and existing codebase here.
> fix: OPTIC-341: CSS inconsistencies which cause conflicts in MonoRepo builds

- src/components/SidePanels/TabPanels/PanelTabsBase.tsx
- src/components/SidePanels/TabPanels/Tabs.tsx
The actual icon width is 8px, and we were putting 20px. This has caused more style issues observed when running the application within MonoRepo context, and should operate correctly regardless of build output if we align the widths correctly.
> fix: OPTIC-341: Incorrect icon width causing layout issues with TabPanels in monorepo

- src/tags/object/RichText/model.js
- src/utils/feature-flags.ts
We already fully sanitize text in view.js with htmlEscape, so it's safe.
We improved html sanitization and this new library started to convert `&` and lonely `>` to html-entites, shifting offsets of the following regions.
`fflag_fix_leap_466_text_sanitization`
To fix the library or its params and we might need it if html tasks are also affected.
> fix: LEAP-466: Don't sanitize text tasks

- src/mixins/Regions.js
Very simple fix. But there is a new UX problem them: if you undo/redo actions done to hidden regions you see no changes on the screen, previously region became visible at some point and only then undo went through actual actions.
none — maybe we need this to cover UX change
> fix: LEAP-368: Don't add `hidden` and `locked` to undo history

- src/utils/bem.ts
It's not used in LSF anyway. And the fix is pretty simple and straightforward.
To fix regexp injection vulnerability https://github.com/HumanSignal/label-studio-frontend/security/code-scanning/9
> fix: LEAP-381: Remove excess regexp from BEM module

- src/components/App/App.js
- src/components/ErrorMessage/ErrorMessage.js
- src/components/InstructionsModal/InstructionsModal.tsx
- src/tags/control/Choice.js
- src/tags/control/Label.js
- src/tags/visual/Style.js
- src/utils/__tests__/html.test.ts
- src/utils/feature-flags.ts
- src/utils/html.js
The primary goal of this PR is to enhance the security and integrity of the Label Studio Frontend (LSF) by introducing HTML sanitization across all components. This effort is in response to the need for a secure environment that effectively neutralizes potential security threats in HTML inputs while maintaining essential functionalities and user experience.
This PR specifically addresses the issue of Cross-Site Scripting (XSS) vulnerabilities in the Label Studio Frontend by implementing proper HTML sanitization in all components that use `dangerouslySetInnerHTML`. The changes ensure that any HTML content rendered through dangerouslySetInnerHTML is thoroughly sanitized, thereby preventing the execution of malicious scripts or XSS attacks. This enhancement …
> fix: LEAP-444: Implement HTML sanitization in LSF

- src/core/Hotkey.ts
- tests/functional/data/core/hotkeys.ts
- tests/functional/specs/core/hotkeys.cy.ts
This PR 
1. wraps unbinding functional to separate keys corectly outside of the keymaster
2. adds alias for `,` to avoid problems with it
3. improves tokenization of hotkeys
Keymaster can't handle unbinding of multiple keys. It also misunderstands `,` and thinks that it is two hotkeys in one (`','` and `''`). So that `,` breaks application in two ways related to each other.
1. we can fix keymaster in a fork (but we did it before and we didn't like it)
2. we can use another library to handle hotkeys. But it's hard to test and integrate.
`Hotkeys`, `Labels`
> fix: LEAP-248: Fix app crashing by hotkeys 

- src/components/App/Grid.js
The "View All Annotations" tab was experiencing loading issues when accessed with a configuration containing an image. The problem stemmed from the validation process, which was impeded by the lazy loading behavior of the image tag. As a result, the image wasn't added to the viewport until fully loaded, causing the tab to fail to load.
To address this issue, the fix involves skipping the validation if the image is marked as ready. This modification acknowledges the lazy load behavior of the image, ensuring that the validation process doesn't impede the loading of the "View All Annotations" tab.
None
no
no
Consideration was given to removing the lazy load from the ImageView to directly address the loading issues. However, it's crucial to note that this alternative …
> fix: LEAP-344: View all annotation tab is not loading

- src/components/RelationsOverlay/RelationsOverlay.js
- src/components/SidePanels/DetailsPanel/Relations.styl
- src/components/SidePanels/DetailsPanel/Relations.tsx
- src/stores/Annotation/Annotation.js
- src/stores/RelationStore.js
- src/tags/control/Relation.js
- src/tags/control/Relations.js
- tests/functional/data/relations/basic.ts
- tests/functional/package.json
- tests/functional/specs/control_tags/taxonomy.cy.ts
- tests/functional/specs/relations/basic.cy.ts
- tests/functional/specs/video_segmentation/regions.cy.ts
- tests/functional/yarn.lock
Previously, TimeTraveler and Relations worked separately. This led to a number of problems when they were used together. Moreover, it violated UX principles. Besides that, the implementation of Relations was based on an legacy paradigm, which was redundant and not entirely suitable. The decision was made to rewrite this functionality to eliminate the described problems.
This fix enables Relations to operate in the context of change history and with undo/redo functionality. It also eliminates the legacy approach to storing the state of Relation.
Now you can undo changes in Relations as it works for regions. 
This may improve performance, as we are reducing the number of traversals through the tag tree and also not creating unnecessary entities in `mst`.
Nope
N/A …
> feat: LEAP-355: Make relations work with TimeTraveler

- src/components/TopBar/Actions.js
- src/components/TopBar/TopBar.js
- src/core/TimeTraveller.js
- src/stores/Annotation/Annotation.js
- src/tags/control/Taxonomy/Taxonomy.js
drafts were being lost when view all was selected, this change ensures they are saved and notifies the user accordingly. 
> feat: OPTIC-107: Draft saving on view all

- src/components/AnnotationTab/AnnotationTab.js
annotationStore was not passed to Comments panel there
This was breaking the app completely when old interface is enabled (2 FFs are OFF) and comments interface is enabled as well.
This bug happens only if those 2 flags are disabled:
- `ff_front_1170_outliner_030222_short`
- `fflag_feat_front_dev_3873_labeling_ui_improvements_short`
Inject AppStore to Comments.tsx as we usually do, but typescript can't understand this injection, so let's just pass it through.
> fix: LEAP-515: Fix CommentForm for old UI

- src/regions/BrushRegion.js
- src/utils/canvas.js
- tests/functional/package.json
- tests/functional/specs/image_segmentation/tools/magic-wand.cy.ts
- tests/functional/yarn.lock
Enhance the new brush mask exporting approach to handle masks created by Magic Wand tool.
The introduction of the feature flag `fflag_feat_front_lsdv_4583_multi_image_segmentation_short` has resulted in a new method for serializing brush masks into RLE (Run-Length Encoding). As a result, the `maskDataUrl` serialization was lost. Consequently, we are no longer able to submit results generated by the Magic Wand tool.
This is an universal solution. No ff is needed.
N/A
`MIG`, `Brush`, `MagicWand`, `Serialization`
> fix: LEAP-439: Add maskData exporting into new MIG serialization approach

- src/core/Hotkey.ts
- src/core/settings/keymap.json
- src/utils/feature-flags.ts
We had the same hotkeys:
1. for the going to next/prev pages in multi-item mode in object tags.
2. for duplicating selected regions
Sometimes it provided unexpected results. So we had to change the hotkeys for going through pages.
`fflag_fix_leap_246_multi_object_hotkeys_160124_short`
`Hotkeys`
> fix: LEAP-246: Replace overlaping MIG hotkeys

- src/tags/object/RichText/model.js
- src/utils/data.js
- tests/functional/specs/object_tags/text.cy.ts
Cherry-picking from #1675
* Fix: LEAP-580: Display non-string values in Text
During recent incident fix we missed conversion to string for Text tag's `value` param.
* Fix deprecated `substr` to `slice` in `parseValue`
* Add cypress test for non-string values
> fix: LEAP-580: Display non-string values in Text

- src/utils/data.js
This PR addresses inefficient regular expressions in the code, as identified by GitHub's code scan. In particular, the regular expression "(?""|[^""]+)*" has been causing performance issues and potential security risks. The goal is to enhance performance and mitigate the risk of Denial of Service ("DoS") attacks. https://github.com/HumanSignal/label-studio/security/code-scanning/760
By optimizing the regular expression, this change improves code performance and reduces the risk of DoS attacks. It ensures that the regular expression matching process is more efficient and not negatively affecting the application's responsiveness.
Yes, this change positively affects performance. The replacement of the inefficient regular expression with the optimized regex "(?:""|[^"])*" significantly …
> fix: LEAP-509: Optimize regular expression for improved performance

- .github/pull_request_template.md
Shorter version of our frontend PR template to encourage and help to make more thoughtful description and highlight important nuances of every PR.
Current PR template usually left (mostly) untouched, because it has lot of items to read and change.
> ci: New PR template

- e2e/tests/ner-text.test.js
- src/components/Node/Node.tsx
- src/components/SidePanels/DetailsPanel/RegionDetails.tsx
- src/components/SidePanels/DetailsPanel/RegionItem.tsx
- src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
- src/components/SidePanels/OutlinerPanel/TreeView.styl
New Outliner dropped this important info from region items in the list.
Returning it back.
We need to remove flags for Outliner and NEW UI, enabling it for everyone. To do this smoothly new UI should be very similar to old ones, and that's one of the most important differences.
Outliner `ff_front_1170_outliner_030222_short`
New UI `fflag_feat_front_dev_3873_labeling_ui_improvements_short`
> fix: LEAP-523: Return region's text to item in a list 

- src/components/ImageView/ImageView.js
- tests/functional/data/image_segmentation/tools/rect.ts
- tests/functional/specs/image_segmentation/tools/rect.cy.ts
We have a functionality under the feature flag that allows us unselect selected region by clicking outside.
Well... It doesn't work with separated tools like `<Rectangle>` tag. So we are going to fix it.
`ff_front_dev_1442_unselect_shape_on_click_outside_080622_short`
`ImageView`, `Image Segmentation`, `Image Tools`
> fix: LEAP-240: Prevent creating region on clicking outside selected one

- src/mixins/PerItem.js
- src/mixins/PerRegion.js
- src/mixins/Regions.js
- src/mixins/Required.js
- src/tags/control/ClassificationBase.js
- src/tags/control/DateTime.js
- src/tags/control/Number.js
- tests/functional/data/control_tags/number.ts
- tests/functional/package.json
- tests/functional/specs/control_tags/number.cy.ts
- tests/functional/yarn.lock
The change was necessary due to failures of the number validation in some cases that resulted in the ability to save invalid values.
This fix introduces value validation for the Number tag, conducts a refactoring of the existing validation code, and implements a per-item mode validation.
Nope
Nope
N/A
N/A
At least it should not.
`Number`, `DateTime`, `Validation`, `Required`, `perItem`
> fix: LEAP-447: Fix Number tag validation 

- src/components/ImageView/Image.js
- src/components/ImageView/ImageView.js
- src/tools/MagicWand.js
- tests/functional/package.json
- tests/functional/specs/relations/basic.cy.ts
- tests/functional/yarn.lock
When both MIG and image preloading are enabled, there was no canvas overlay for the Magic Wand which caused the Magic Wand to fail.
Not really covered but affected by:
`fflag_feat_front_lsdv_4583_6_images_preloading_short`
`fflag_feat_front_dev_4081_magic_wand_tool`
https://github.com/HumanSignal/label-studio-frontend/pull/1327
But we believe that it's not neccesary since the way Magic Wand works [was fixed recently](https://github.com/HumanSignal/label-studio/pull/5246) and potentially we don't need async stuff.
`Multy Image Segmentation`, `Magic Wand`
> fix: LEAP-148: Fix MagicWand in MIG scenario with image preloading

- src/components/TopBar/Actions.js
- src/components/TopBar/TopBar.js
- src/stores/Annotation/store.js
We should save draft when user clicks on View All, but we should save it only if there are changes made to annotation.
Draft is created/updated **every** time user click on View All, even if that's fresh new task, if there are no changes, if draft was saved a second ago.
We could add checks for actual changes to `saveDraftImmediatelyWithResults()`, but the whole approach should be revisited. So current fix is a quick patch for the actual problem.
Also the main reason for draft not being saved is the check for `editable` in `saveDraft()` — at this moment View All is already displayed and all annotations are not editable. Most probably it will be enough just to rewrite this check to check for annotation explicitly.
> fix: LEAP-640: Don't save empty draft on View All

- e2e/package.json
- e2e/yarn.lock
- package.json
- src/components/NewTaxonomy/NewTaxonomy.tsx
- yarn.lock
updating dependency to address vulnerability
> fix: OPTIC-411: [lsp] Fix Follow Redirects improperly handles URLs in the url.parse() function

- src/tags/object/Text.js
Text tag is displayed as html, so all spaces are smashed by browser, and they also go like this to result. To avoid this users can add custom style in config, described in docs. But it only says that this affects displaying, not saving the result. Adding this note as well.
https://github.com/HumanSignal/label-studio/issues/5338
> docs: LEAP-615: Mention spaces saving for Text tag

- e2e/tests/helpers.js
- e2e/tests/image.transformer.test.js
- e2e/tests/maxUsage.test.js
- e2e/tests/regression-tests/brush-relations.test.js
- e2e/tests/regression-tests/image-width.test.js
- src/LabelStudio.tsx
There are external places that can call `destroy()` unconditionally, so having it uninitialized is dangerous and leads to app crash.
Note: 4 e2e tests are disabled waiting for #1708
App was crashing in Config Preview (editor) when you use config with `Image` tag and change its `value` resulting in error `f.current.destroy is not a function`
That only happens with `fflag_feat_front_lsdv_4583_6_images_preloading_short` ON
And despite the change was introduced in #1640 it happens even with `fflag_fix_front_leap_443_select_annotation_once` OFF
Check what's going on with image preloading that forces Preview to destroy LSF in some different way. Will do this later.
> fix: LEAP-740: Don't use destroy = null
